### ISSUE TITLE
특정 표가 깨져서 내용이 생략(?)되는 문제 발생

### ISSUE THREAD

**Issue by gaon12** [dodawiki/mediawiki-namumark#13]
같은 코드로 작성된 서로 다른 사이트(하나는 나무마크 적용, 다른 하나는 나무마크 미적용)에서 나온 결과물입니다.

![www](https://user-images.githubusercontent.com/34927797/145025778-8dbccd88-4dfb-4dfd-bd4e-e53bfa2dd63f.jpg)
첫번째 이미지는 나무마크를 적용하지 않은 사이트이고,

![beta](https://user-images.githubusercontent.com/34927797/145025837-d02f3a34-b2bb-4ce1-af0a-89ab99c4d316.jpg)
두번째 이미지는 나무마크를 적용한 사이트입니다.

서로 같은 코드를 사용했는데, 표가 깨지는 문제가 발생합니다.

혹시 몰라 링크 첨부합니다. 확인해 주세요.
* 나무마크 미적용 사이트(https://www.gaonwiki.com/w/틀:Halyosy_합창곡)
* 나무마크 적용 사이트(https://beta.gaonwiki.com/w/테스트)

**Comment by xeruel** [comment]
미디어위키 표 문법이랑 the seed 표 문법이 충돌해서 표 상단 일부와 파이프 문자 2개(||)로 감싸진 부분만 표로 인식되는 것 같습니다.

**Comment by gaon12** [comment]
> 미디어위키 표 문법이랑 the seed 표 문법이 충돌해서 표 상단 일부와 파이프 문자 2개(||)로 감싸진 부분만 표로 인식되는 것 같습니다.

그럼 버그가 아니라는 건가요?

**Comment by xeruel** [comment]
나무위키에서는 표로 인식되지 않는 걸 보면 버그는 맞긴 한 것 같습니다.

**Comment by ddarkr** [comment]
![image](https://user-images.githubusercontent.com/6638675/145063160-bddc51ae-de7f-4ec8-84bf-dbecece924a6.png)

미디어위키 표 괄호인 `{|`에서는 테이블 처리를 비활성화하는 것으로 대응하였습니다.
