### ISSUE TITLE
Widgets 확장기능과 충돌

### ISSUE THREAD

**Issue by gaon12** [dodawiki/mediawiki-namumark#16]
Widgets 확장기능을 사용하여 Disqus를 띄우고 있는데요.
미디어위키 표 문법과 충돌한 문제를 해결한 이슈 #13 인 93b6c56601ad434c6a3a2d5aff669a16e0cbe376 커밋을 한 이후에는, Widgets 확장기능과 충돌하여 Disqus를 불러오지 못하는, 정확히는 Widget을 불러오지 못하는 문제가 있습니다.

혹시나 해서 나무마크를 끄고 새로고침을 하니 Widget을 제대로 불러옵니다. 확인 부탁드립니다.

**Comment by ddarkr** [comment]
1. 우선 확장 기능에 대한 개별 대응은 지원 계획이 없습니다.
2. 93b6c56601ad434c6a3a2d5aff669a16e0cbe376 커밋과 `{{#widget}}` 파서 펑션의 연관성은 없는 것 같습니다.
3. 나무마크 확장 기능의 버그라고 파악된다면, 문제점과 충돌이 발생하는 부분(GitHub 링크)을 첨부해주시면 감사하겠습니다.

**Comment by gaon12** [comment]
> 1. 우선 확장 기능에 대한 개별 대응은 지원 계획이 없습니다.
> 2. [93b6c56](https://github.com/dodawiki/mediawiki-namumark/commit/93b6c56601ad434c6a3a2d5aff669a16e0cbe376) 커밋과 `{{#widget}}` 파서 펑션의 연관성은 없는 것 같습니다.
> 3. 나무마크 확장 기능의 버그라고 파악된다면, 문제점과 충돌이 발생하는 부분(GitHub 링크)을 첨부해주시면 감사하겠습니다.

[93b6c56](https://github.com/dodawiki/mediawiki-namumark/commit/93b6c56601ad434c6a3a2d5aff669a16e0cbe376) 이전 커밋으로 테스트 해 보았는데 여전히 문제가 발생합니다. → 연관성 없는것 같습니다. 감사합니다.

로그를 아무리 봐도 어디서 충돌하는지 모르겠네요.

일단 widgets 확장기능 사용을 중지해야겠습니다. 답변 감사합니다.
