### ISSUE TITLE
틀에서 #!wiki 사용 후 틀 끼워넣기 시 오류가 있습니다. 

### ISSUE THREAD

**Issue by HyangRim** [dodawiki/mediawiki-namumark#18]
안녕하세요. mediawiki-namumark를 이용하는 사람입니다. 다름이 아니라 틀:문서 를 만들고 그 틀을 {{틀:문서}}혹은 
[include(틀:문서)] 같은 방식으로 다른 곳에서 불러올 경우에 불러온 문서에서는 #!wiki쪽이 제대로 출력이 안되는 거 같습니다. 
혹 여유가 되신다면, 해결 방안에 대해서 대략적으로나마 조언 혹은 수정에 대해서 알려주셨으면 합니다. 
![캡처1](https://user-images.githubusercontent.com/24820033/148091636-0356b089-7afe-4c59-8af1-d852ec7406a8.JPG)
![캡처2](https://user-images.githubusercontent.com/24820033/148091652-152da279-0233-445a-be63-09a6c9940ff2.JPG)
![캡처3](https://user-images.githubusercontent.com/24820033/148091660-9c0544fd-8e78-46dc-81df-28854e8e56e9.JPG)
![캡처4](https://user-images.githubusercontent.com/24820033/148091669-7fb208ff-7c42-450d-bebd-4e9be9c7c40a.JPG)

**Comment by ddarkr** [comment]
- 수정합니다.

문제점 파악을 잘못했네요... 죄송합니다. 해결법 찾아보고 다시 코멘트하겠습니다

**Comment by HyangRim** [comment]
감사합니다.

**Comment by ddarkr** [comment]
PR #19, 릴리즈 `v10.3.2` 기준으로 해당 문제는 수정되었습니다.

**Comment by HyangRim** [comment]
감사합니다. 늦은 새벽인데 고생많으셨습니다!! 덕분에 많은 도움이 되고있습니다..

**Comment by Jeongyong-park** [comment]
@ddarkr  v10.3.2 사용 중인데 동일한 증상이 있는것 같습니다.
[문제가 되는 곳](https://hamwiki.kr/index.php/Alinco)

**Comment by ddarkr** [comment]
@Jeongyong-park 해당 문제는 유사한 오류긴 하나, 다른 부분에서 발생한 문제로 보입니다.

이슈를 #20 으로 분리합니다.
