### ISSUE TITLE
틀 임포트 시 `{{{#! }}}` 문법 렌더링 오류 

### ISSUE THREAD

**Issue by ddarkr** [dodawiki/mediawiki-namumark#20]
https://github.com/dodawiki/mediawiki-namumark/issues/18#issuecomment-1014611725

![image](https://user-images.githubusercontent.com/6638675/149802921-eed11729-0603-422b-a13c-b0934e3cb68a.png)

틀 렌더링에서 문제가 발생함

**Comment by ddarkr** [comment]
최근 위키에 신경 쓸 여력이 없어서, 해결이 좀 늦어질 수 있습니다. 죄송합니다.

**Comment by Jeongyong-park** [comment]
> 최근 위키에 신경 쓸 여력이 없어서, 해결이 좀 늦어질 수 있습니다. 죄송합니다.

부탁 드립니다...

**Comment by ddarkr** [comment]
Fixed at 5cfb59433de31ccd6b27b3ccc4a8888af6e3d02c

`v10.3.3` 버전에서 수정되었습니다. 확장 기능 업데이트 후 사용해주세요.
