### ISSUE TITLE
Remove usage of ParserBeforeStrip and ParserBeforeTidy

### ISSUE THREAD

**Issue by PlavorSeol** [dodawiki/mediawiki-namumark#4]
Both [`ParserBeforeStrip`](https://www.mediawiki.org/wiki/Manual:Hooks/ParserBeforeStrip) and [`ParserBeforeTidy`](https://www.mediawiki.org/wiki/Manual:Hooks/ParserBeforeTidy) were deprecated in 1.35 and removed in 1.36.
Currently `NamuMarkCore::NamuMark` and `NamuMarkCore::NamuMarkHTML2` are [using these hooks](https://github.com/dodawiki/mediawiki-namumark/blob/master/extension.json#L31-L32) and they should be removed and replaced.
Ideally parsing of Namumark syntax should entirely be done using [`InternalParseBeforeLinks`](https://www.mediawiki.org/wiki/Manual:Hooks/InternalParseBeforeLinks) and use [`ParserAfterTidy`](https://www.mediawiki.org/wiki/Manual:Hooks/ParserAfterTidy) to add any HTML content that MediaWiki parser do not normally allows, rather than relying on [`$wgRawHtml`](https://www.mediawiki.org/wiki/Manual:$wgRawHtml) setting.

**Comment by ddarkr** [comment]
말씀해주신 `$wgRawHtml`를 제거해도 파싱에 문제가 없어보이긴 하는데, 나중에 다시 확인이 필요하다고 생각됩니다.
아직 저도 나무마크 PHP 버전의 구조를 모두 파악하질 못해서... 유지보수가 미숙합니다.
