### ISSUE TITLE
20만 바이트 이상에서의 버그 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by DGTaeHyeon** [dodawiki/mediawiki-namumark#6]
우선은 미디어위키 1.36.0을 이용해 위키를 꾸려가고 있는 한국인 유저임을 밝히고 이 글을 시작합니다.

 미디어위키 1.36.0에 대응되는 버전이 나오면 미디어위키 나무마크 확장기능의 이 필드를 설치하려고 고민하고 있습니다. 하지만, 한가지 걸리는 부분이 있다면 미디어위키 나무마크 확장기능의 원래 버전부터 고질적으로 가지고 있던 20만 바이트 이상에서의 버그입니다.

어떤 한 문서가 20만 바이트 이상이 되면 치명적인 오류가 발동해 문서가 오류투성이로 뒤덮인다고 들었습니다. 실제로 그것때매 어떤 위키는 미디어위키 나무마크 확장기능에 대한 지원을 중지한 사례도 있고요. 그래서 20만 바이트 이상에서의 버그는 유지보수 과정에서 잡을 계획이 있으신가 질문드립니다.

**Comment by ddarkr** [comment]
안녕하세요. 확장 기능에 관심 가져주셔서 감사드립니다.

말씀해주신 내용을 보고 미디어위키 1.35.2 환경에서 20만 바이트 이상의 문서를 임의로 생성하여 테스트하였을 때 문법 파싱에는 문제가 없는 것으로 확인되었습니다.

추후의 미디어위키 버전에서 사용 중에 문제가 발생한다면, 제 능력이 닿는 한에서는 유지보수를 할 생각입니다.


테스트 문서: https://wiki.ddark.kr/%EC%82%AC%EC%9A%A9%EC%9E%90:Doda/%ED%85%8C%EC%8A%A4%ED%8A%B81
테스트 문서 정보: https://wiki.ddark.kr/index.php?title=%EC%82%AC%EC%9A%A9%EC%9E%90:Doda/%ED%85%8C%EC%8A%A4%ED%8A%B81&action=info

감사합니다 😎

**Comment by DGTaeHyeon** [comment]
유지보수 필드 개발 과정에서 버전에 맞게 고쳐져, 자연스럽게 해결된 것으로 알겠습니다. 고맙습니다!
