### ISSUE TITLE
오류 관련해서 보고 드립니다.

### ISSUE THREAD

**Issue by DGTaeHyeon** [dodawiki/mediawiki-namumark#7]
저번에 해당 확장기능과 관련하여 문의사항을 물어본 유저입니다. 제가 운영하는 위키에서 제가 만든 문서들을 대상으로 삼아 시험한 결과, 해당 확장기능을 도입하기를 꺼리거나 고민하는 위키들이 생각한 오류는 거의 없었으며, 예상치 못한 오류가 터져나왔습니다. 저는 이것들을 그냥 기억으로만 넘기는 대신에 다른 위키들도 도입을 위해서 보고 도입에 참고 및 결정하라는 의미에서 제 사용자 문서 하위에 기록으로 남겼으나... 선거정보 틀이 깨진 것은 구조적 문제 상으로 도다님께 전달해야겠다는 마음을 먹고 보고를 드리게 됐습니다.

자세한 것은 아래 링크에 나와있습니다. 도다님께서도 이러한 오류를 살피시어 확장기능의 유지보수에 긴히 사용해주시기를 부탁드립니다.

※참고로, 제가 운영하는 위키는 세계 설정을 통해 세계관을 창작해내는 위키입니다. 이 점 유의하여 보시기를 바라겠습니다.

https://www.thestories.kr/wiki/%EC%82%AC%EC%9A%A9%EC%9E%90:%EB%AF%B8%EB%A5%B4%EC%B2%B4%EC%95%84_%EC%A7%80%EC%9A%B0%EB%A5%B4%EC%A7%80%EC%9A%B0/%EC%98%A4%EB%A6%AC%EB%A7%88%ED%81%AC_%EC%8B%A4%EC%A6%9D%EC%8B%9C%ED%97%98_%EC%A0%90%EA%B2%80#.EC.98.88.EC.83.81.EC.B9.98_.EB.AA.BB.ED.95.9C_.EC.98.A4.EB.A5.98.EC.9D.98_.EB.B0.9C.EC.83.9D

**Comment by ddarkr** [comment]
안녕하세요. 제보해주신 버그에 대해 확인하였고 원인을 분석하느라 시간이 좀 걸렸습니다.

## tl;dr

- #8 에서 해결. (release `v10.2.1`)
- 문법 앞에 띄어쓰기를 사용하시는 경우 장기적으로 문제가 발생할 수 있으니, 가능하면 붙여서 표기하시는 것을 권장합니다.


## 문제 해결

[나무위키 들여쓰기 문법](https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%AC%B8%EB%B2%95%20%EB%8F%84%EC%9B%80%EB%A7%90/%EC%8B%AC%ED%99%94#s-4)을 처리하는 `NamuMarkExtra`@`indent`에서의 정규식 처리에 문제가 있었습니다.

[구버전의 처리 정규식](https://github.com/dodawiki/mediawiki-namumark/blob/10ca3620e0e94542e6d246df70866e1e8f19eb6c/includes/NamuMarkExtra.php#L15) 구문이 문단 앞에 띄어쓰기를 모두 들여쓰기로 간주하여 들여쓰기 처리합니다. 여기서 문제가 발생하는데, 해당 확장의 특성 상 미디어위키 문법 파서가 동작하기 전에 나무마크 파서를 동작 시키기 때문에 문제가 발생했습니다.

![image](https://user-images.githubusercontent.com/6638675/133474894-4c9bd3ae-41d0-43fb-b861-bfea7e117f45.png)

indent 파서가 먼저 들여쓰기를 처리하여, 이후에 처리되는 미디어위키 파서가 이미 문법 처리된 틀 문법을 인식하지 못한 문제로 보입니다.

나무위키가 들여쓰기 문법에서도 `[include()]` 문법을 지원하고 있어 해당 문제점에 대해 지원하기로 결정하였습니다. 다만 구조 상의 문제로 나무위키처럼 틀에도 들여쓰기가 지원되지는 않습니다.

해당 문제점에 대한 패치는 `v10.2.1`로 `master` 브랜치에 올라갔습니다. 감사합니다.

## 추가적으로

하지만 나무마크가 문단 앞 띄어쓰기를 들여쓰기 문법으로 사용하고 있기 때문에, 장기적으로 봤을 때는 틀 문법 혹은 표 문법 등의 띄어쓰기를 제거해주시는게 적합하다고 보여집니다.

해당 패치로 인한 문법 파싱에 문제점이 발생 될 경우 롤백될 수 있습니다 😥

**Comment by DGTaeHyeon** [comment]
버그를 제보하려고 실증시험 결과를 기록한 것에서 선거결과 표 관련 오류의 예시가 누락된 것이 있어 급히 예시를 넣었습니다.

이 점 살펴서 버그 해결에 사용하시기를 긴히 부탁드립니다.

**Comment by ddarkr** [comment]
@DGTaeHyeon 나무마크를 적용함으로써 발생하는 문제와 정상적인 출력을 **새 이슈**로 남겨주시기 바랍니다.

또한, 나무마크의 정상 작동으로 인한 기존 틀 문법에 대한 문제(미디어위키 문법 호환)에 대한 해결은 계획이 없습니다. 나무마크를 피하시어 해당되는 내용을 수정하시기 바랍니다.
