### ISSUE TITLE
도다마크 10.2.1 버전에서 표시 오류가 발생합니다.

### ISSUE THREAD

**Issue by xeruel** [dodawiki/mediawiki-namumark#9]
안녕하세요, 스포어 위키 관리자 제르엘입니다.
스포어 위키 적용을 위해 개인 위키에서 미디어위키 1.36 버전을 테스트하던 중, 아래와 같은 현상을 발견하여 제보합니다.

- ~~목차에 테두리가 생기는 현상~~
- 일부 틀 사이를 띄어 썼을 때 줄바꿈이 일어나는 현상
- 문단과 문단 사이를 비울 경우 줄바꿈이 일어나는 현상
- [[링크|{{{#nnnnnn 링크}}}]] 형식과 같이 하이퍼링크에 색상을 적용할 경우 {{글씨 색| #nnnnnn|링크}}와 같은 형식으로 깨져 버리는 현상

자세한 상황 및 문서 원본은 아래의 Bittersweets 게시글에 첨부해 두었습니다. 해당 개인 위키가 민감한 정보를 다루고 있는지라 문제가 되는 문서는 공개할 수 없습니다. 죄송합니다.

감사합니다.

----
https://bittersweets.kr/?p=4983
비밀번호는 현재 도다님 위키에서 사용중인 스킨의 영문 이름입니다(대소문자 구분).

**Comment by xeruel** [comment]
혼선을 드려서 죄송합니다. 미디어위키 1.36 버전이 아니라 도다마크 최신 버전에서 발생하는 오류 같습니다. 대조 버전은 10.2 버전입니다.

* 목차에 테두리가 생기는 현상은 미디어위키 1.36 버전의 특성인 것 같습니다.

**Comment by ddarkr** [comment]
안녕하세요 😊 확장 기능을 사용해주셔서 감사드립니다.

다음과 같은 문제는 제가 유지보수 하고 있는 확장에서 발생하는 문제로 파악되었습니다. (미디어위키 버전과는 무관합니다)

- 일부 틀 사이를 띄어 썼을 때 줄바꿈이 일어나는 현상
- 문단과 문단 사이를 비울 경우 줄바꿈이 일어나는 현상
- [[링크|{{{#nnnnnn 링크}}}]] 형식과 같이 하이퍼링크에 색상을 적용할 경우 {{글씨 색| #nnnnnn|링크}}와 같은 형식으로 깨져 버리는 현상

다시 언급해주셨지만, 다음 문제는 나무마크와 연관되어 있지 않은 문제입니다.

- 목차에 테두리가 생기는 현상
  - 약간 여담이지만, 미디어위키 스타일을 Liberty 스킨이 override 하는 부분이 있습니다. 미디어위키 업그레이드로 인하여 TOC style이 변경되어 발생하는 문제가 아닐까 추측해봅니다.

해당 문제점을 해결하는 대로 이슈에 언급하도록 하겠습니다.

**Comment by xeruel** [comment]
확인해 주셔서 감사합니다. 언제나 수고가 많으십니다!

**Comment by ddarkr** [comment]
빠르게 문제를 파악하고 수정하여, tag `v10.3`에 오류 해결 버전을 릴리즈하였습니다.

버그를 수정에 도움을 주셔서 감사드립니다 😉

**Comment by xeruel** [comment]
혹시 가능하다면 도다님 위키의 틀:노말타입 문서와 틀:풀타입 문서의 삭제 코멘트를 숨겨주실 수 있나요? 삭제 코멘트에 틀 문법이 전부 적혀 있는데, 해당 틀 출처가 나무위키라서 저작권 문제가 발생할 수 있을 것 같습니다.

닫힌 이슈에 코멘트 남겨서 죄송합니다.

+) 가능하다면 테스트 문서 삭제 코멘트도 숨겨주시면 감사하겠습니다.

**Comment by ddarkr** [comment]
@xeruel 삭제 처리해드렸습니다. 불편을 드려 죄송합니다 😅

**Comment by xeruel** [comment]
저야말로 불편을 드려 죄송합니다. 빠른 처리 감사합니다!
